// src/components/Footer/Footer.jsx
import * as React from 'react'
import './Footer.css'

const getCopyrightYear = () => {
  const initYear = 2017
  const d = new Date()
  const y = d.getFullYear()
  return y > initYear ? `${initYear}–${y}` : initYear.toString()
}

const author = 'Ian A. Cook'
const authorURL = 'https://github.com/nai888'
const appGhURL = 'https://github.com/nai888/langua'

const Footer = () => (
  <footer>
    <div className='footer'>
      <p className='copyright'>
        <a
          href={appGhURL + '#versioning'}
          target='_blank'
          rel='noopener noreferrer'
        >
          Version
          {' '}
          <i
            className='fas fa-code'
          />
          {' '}
          0.1.0
        </a>
        . Built by
        {' '}
        <a
          href={authorURL}
          target='_blank'
          rel='noopener noreferrer'
        >
          {author}
        </a>
        , copyright
        {' '}
        <i
          className='far fa-copyright'
        />
        {' '}
        {getCopyrightYear()} under the
        {' '}
        <a
          href='https://choosealicense.com/licenses/agpl-3.0/'
          target='_blank'
          rel='noopener noreferrer'
        >
          AGPL-3.0
          {' '}
          <i
            className='fas fa-gavel'
          />
          {' '}
          license
        </a>
        .
        {' '}
        <a
          href='https://github.com/nai888/langua'
          target='_blank'
          rel='noopener noreferrer'
        >
          View this project on
          {' '}
          <i
            className='fab fa-github'
          />
          {' '}
          GitHub
        </a>
        .
      </p>
    </div>
  </footer>
)

export default Footer

// src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.sass']
})
export class FooterComponent {
  private getCopyrightDates(): string {
    const initYear = 2017
    const d = new Date()
    const y = d.getFullYear()

    if (y > initYear) {
      return `${initYear}–${y}`
    } else {
      return initYear.toString()
    }
  }

  author = 'Ian A. Cook'
  authorURL = 'https://github.com/nai888'
  copyYear = this.getCopyrightDates()
  appGhURL = 'https://github.com/nai888/langua'
}

<footer>
  <div class="footer">
    <p class="copyright"><a [href]="appGhURL + '#versioning'" target="_blank" ref="noopener noreferrer">Version 0.1.0</a>. Built by <a [href]="authorURL" target="_blank" rel="noopener noreferrer">{{author}}</a>, copyright &copy; {{copyYear}} under the <a href="https://choosealicense.com/licenses/agpl-3.0/" target="_blank" rel="noopener noreferrer">AGPL-3.0 license</a>. <a [href]="appGhURL" target="_blank" rel="noopener noreferrer">View this project on GitHub</a>.</p>
  </div>
</footer>
