// src/components/Morph/Morph.jsx
import * as React from 'react'
import injectSheet from 'react-jss'
import styles from './styles'

const Morph = () => (
  <div className='morph'>
    <h2 class='tool-title'>LanguaMorph</h2>
    <p class='notice'>This tool is still in planning.</p>
  </div>
)

export default injectSheet(styles)(Morph)

// src/app/morph/morph.component.ts
import { Component } from '@angular/core'
import { Title } from '@angular/platform-browser'

@Component({
  selector: 'app-morph',
  templateUrl: './morph.component.html',
  styleUrls: ['./morph.component.sass']
})
export class MorphComponent {
  constructor(private titleService: Title) {
    titleService.setTitle('Langua | Morph')
  }
}

<h2 class="tool-title">LanguaMorph</h2>
<p class="notice">This tool is still in planning.</p>
