// src/components/Frequen/Frequen.jsx
import React from 'react'
import injectSheet from 'react-jss'
import styles from './styles'

const Frequen = () => (
  <div className='frequen'>
    <h2 class='tool-title'>LanguaFrequen</h2>
    <p class='notice'>This tool is still in planning.</p>
  </div>
)

export default injectSheet(styles)(Frequen)

// src/app/frequen/frequen.component.ts
import { Component } from '@angular/core'
import { Title } from '@angular/platform-browser'

@Component({
  selector: 'app-frequen',
  templateUrl: './frequen.component.html',
  styleUrls: ['./frequen.component.sass']
})
export class FrequenComponent {
  constructor(private titleService: Title) {
    titleService.setTitle('Langua | Frequen')
  }
}

<h2 class="tool-title">LanguaFrequen</h2>
<p class="notice">This tool is still in planning.</p>
