// src/app/header/header.component.ts
import { Component } from '@angular/core'
import { ActivatedRoute, Router } from '@angular/router'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  constructor(
    private route: ActivatedRoute,
    private router: Router
  ) { }
  siteTitle = 'Langua'
  siteSubtitle = 'A suite of language tools'
}

<header>
  <div class="header">
    <div class="title-area">
      <h1 class="site-title"><a routerLink="/">{{siteTitle}}</a></h1>
      <p class="site-subtitle">{{siteSubtitle}}</p>
    </div>
    <nav>
      <ul class="menu">
        <li><a routerLink="/gen" routerLinkActive="active">Gen</a></li>
        <li><a routerLink="/morph" routerLinkActive="active">Morph</a></li>
        <li><a routerLink="/deriv" routerLinkActive="active">Deriv</a></li>
        <li><a routerLink="/frequen" routerLinkActive="active">Frequen</a></li>
      </ul>
    </nav>
  </div>
</header>

// src/components/Header/Header.jsx
import * as React from 'react'
import { Link, NavLink } from 'react-router-dom'
import './Header.css'

const siteTitle = 'Langua'
const siteSubtitle = 'A suite of language tools'

const Header = () => (
  <header>
    <div className='header'>
      <div class='title-area'>
        <h1 class='site-title'><Link to='/'>{siteTitle}</Link></h1>
        <p class='site-subtitle'>{siteSubtitle}</p>
      </div>
      <nav>
        <ul class='menu'>
          <li><NavLink to='/gen' activeClassName='active'>Gen</NavLink></li>
          <li><NavLink to='/morph' activeClassName='active'>Morph</NavLink></li>
          <li><NavLink to='/deriv' activeClassName='active'>Deriv</NavLink></li>
          <li><NavLink to='/frequen' activeClassName='active'>Frequen</NavLink></li>
          <li><NavLink to='/tree' activeClassName='active'>Tree</NavLink></li>
        </ul>
      </nav>
    </div>
  </header>
)

export default Header
