// src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  private getCopyrightDates(): string {
    const initYear = 2017
    const d = new Date()
    const y = d.getFullYear()

    if (y > initYear) {
      return `${initYear}–${y}`
    } else {
      return initYear.toString()
    }
  }

  author = 'Ian A. Cook'
  authorURL = 'https://github.com/nai888'
  copyYear = this.getCopyrightDates()
}

<footer>
  <div class="footer">
    <p class="copyright">Built by <a [href]="authorURL" target="_blank" rel="noopener noreferrer">{{author}}</a>, copyright &copy; {{copyYear}} under the <a href="https://choosealicense.com/licenses/agpl-3.0/" target="_blank" rel="noopener noreferrer">AGPL-3.0 license</a>. <a href="https://nai888.github.io/langua/" target="_blank" rel="noopener noreferrer">View this project on GitHub</a>.</p>
  </div>
</footer>

// src/components/Footer.jsx
import * as React from 'react'

const getCopyright = () => {
  const initYear = 2017
  const d = new Date()
  const y = d.getFullYear()
  return y > initYear ? `${initYear}–${y}` : initYear.toString()
}

const Footer = () => (
  <footer>
    <p>
      Built by
      {' '}
      <a
        href='https://github.com/nai888/'
        target='_blank'
        rel='noopener noreferrer'
      >
        Ian A.&nbsp;Cook
      </a>
      , copyright &copy; {getCopyright()}.
      {' '}
      <a
        href='https://github.com/nai888/langua'
        target='_blank'
        rel='noopener noreferrer'
      >
        View this project on GitHub.
        {' '}
        <i
          className='fab fa-github'
        />
      </a>
    </p>
  </footer>
)

export default Footer
