// src/app/deriv/deriv.component.ts
import { Component } from '@angular/core'
import { Title } from '@angular/platform-browser'

@Component({
  selector: 'app-deriv',
  templateUrl: './deriv.component.html',
  styleUrls: ['./deriv.component.sass']
})
export class DerivComponent {
  constructor(private titleService: Title) {
    titleService.setTitle('Langua | Deriv')
  }
}

<h2 class="tool-title">LanguaDeriv</h2>
<p class="notice">This tool is still in planning.</p>

// src/components/Deriv/Deriv.jsx
import * as React from 'react'
import injectSheet from 'react-jss'
import styles from './styles'

const Deriv = () => (
  <div className='deriv'>
    <h2 class='tool-title'>LanguaDeriv</h2>
    <p class='notice'>This tool is still in planning.</p>
  </div>
)

export default injectSheet(styles)(Deriv)
