// src/app/tree/tree.component.ts
import { Component } from '@angular/core'
import { Title } from '@angular/platform-browser'

@Component({
  selector: 'app-tree',
  templateUrl: './tree.component.html',
  styleUrls: ['./tree.component.sass']
})
export class TreeComponent {
  constructor(private titleService: Title) {
    titleService.setTitle('Langua | Tree')
  }
}

<h2 class="tool-title">LanguaTree</h2>
<p class="notice">This tool is still in planning.</p>

// src/components/Tree/Tree.jsx
import React from 'react'
import injectSheet from 'react-jss'

import styles from './styles'

const Tree = ({classes}) => (
  <div className={classes.tree}>
    <h2 className='tool-title'>LanguaTree</h2>
    <p className='notice'>This tool is still in planning.</p>
  </div>
)

export default injectSheet(styles)(Tree)
